### ISSUE TITLE
Missing Channel specific Authorization Check

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-servicenow#144] opened 2022-12-13 15:58 UTC
#### Description
The ServiceNow plugin does not check if user has access to the specified channel Id while performing any actions like:
- adding a subscription
- listing a subscription
- editing a subscription
- deleting a subscription
- sharing a record. 

#### Impact  
As a result, a user who does not have permissions to a specific private channel (or) a Guest user who has limited permissions, will be able to publish notifications in a channel the user is not part of.

**Comment by ayusht2810** [comment] 2022-12-28 13:48
@asatkinson These are fixed so please verify and close

**Comment by ayusht2810** [comment] 2023-05-31 12:36
@mickmister the issue is fixed. Please verify and close.

**Comment by mickmister** [comment] 2023-07-06 17:31
Fixed with https://github.com/mattermost/mattermost-plugin-servicenow/pull/151

**Closed by mickmister** 2023-07-06 17:31 UTC
