### ISSUE TITLE
Exposure of Emails of ServiceNow Users

### ISSUE THREAD

**Issue by asatkinson** [mattermost/mattermost-plugin-servicenow#150] opened 2022-12-13 16:06 UTC
#### Description
Mattermost allows an option to hide Email Addresses. This can be configured from System Console > Site Configuration > Users and Teams > Show Email Address. 

When this configuration is disabled, it is expected that none of the API endpoints reveal email addresses of any users. However during analysis, it was found that the API endpoint `/plugins/mattermost-plugin-servicenow/api/v1/users` responds back with the email address of the user like this:

```
[{"mattermostUserID":"kwbr6bgi4tbpzjyuig1f8ai5mw","username":"sysadmin","serviceNowUser":{"sys_id":"6816f79cc0a8016401c5a33be04be441","email":"success+sysadmin@simulator.amazonses.com","user_name":"admin"}}]
```

### Impact
Exposure of sensitive private information, i.e. `Email Address`. 

### Suggested Fix
Sanitize and remove the email information before responding back to the API request.

--------------------------

**Comment by ayusht2810** [comment] 2022-12-28 13:50
@asatkinson These are fixed so please verify and close

**Comment by ayusht2810** [comment] 2023-05-31 12:37
@mickmister the issue is fixed. Please verify and close

**Comment by mickmister** [comment] 2023-07-06 17:30
Fixed with https://github.com/mattermost/mattermost-plugin-servicenow/pull/151

**Closed by mickmister** 2023-07-06 17:30 UTC
